# Generated by Django 6.0.6 on 2026-06-25 20:22

import legal_twin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_twin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizendocument',
            old_name='title',
            new_name='description',
        ),
        migrations.AddField(
            model_name='citizendocument',
            name='folder_name',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='citizendocument',
            name='document_type',
            field=models.CharField(choices=[('id_card', 'ID Card'), ('passport', 'Passport'), ('license', 'License'), ('certificate', 'Certificate'), ('employment_contract', 'Employment Contract'), ('court_document', 'Court Document'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='citizendocument',
            name='file',
            field=models.FileField(upload_to=legal_twin.models.document_upload_path),
        ),
    ]
