# Generated by Django 6.0.6 on 2026-06-25 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('labor', 'Labor Law'), ('family', 'Family Law'), ('civil', 'Civil Law'), ('criminal', 'Criminal Law'), ('property', 'Property Law'), ('commercial', 'Commercial Law'), ('administrative', 'Administrative Law'), ('other', 'Other')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('analyzed', 'Analyzed'), ('waiting_documents', 'Waiting Documents'), ('ready', 'Ready'), ('resolved', 'Resolved')], default='draft', max_length=30)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_confidence', models.FloatField(default=0)),
                ('risk_level', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
