# Generated by Django 6.0.6 on 2026-06-26 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_path', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('risk_level', models.CharField(blank=True, max_length=30)),
                ('confidence', models.FloatField(default=0)),
                ('relevant_laws', models.JSONField(blank=True, default=list)),
                ('suggested_actions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='legal_path.legalrequest')),
            ],
            options={
                'verbose_name_plural': 'AI analyses',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('is_actioned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legal_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='legal_path.legalrequest')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_uploaded', models.BooleanField(default=False)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='legal_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legal_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='legal_path.legalrequest')),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=30)),
                ('estimated_days', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legal_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_steps', to='legal_path.legalrequest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Case Created'), ('analyzed', 'Case Analyzed'), ('document_uploaded', 'Document Uploaded'), ('step_completed', 'Step Completed'), ('recommendation_added', 'Recommendation Added'), ('status_change', 'Status Change'), ('note', 'Note')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legal_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='legal_path.legalrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
