# Generated by Django 4.2.29 on 2026-06-26 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legal_path', '0002_aianalysis_recommendation_requireddocument_and_more'),
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('complaint', 'Complaint'), ('appeal', 'Appeal'), ('petition', 'Petition'), ('administrative_request', 'Administrative Request'), ('employment_complaint', 'Employment Complaint'), ('rental_complaint', 'Rental Complaint'), ('power_of_attorney', 'Power of Attorney'), ('contract', 'Contract')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('structure', models.TextField()),
                ('required_fields', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(default='fr', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(max_length=50)),
                ('situation', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('language', models.CharField(default='fr', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('edited', 'Edited'), ('archived', 'Archived')], default='generated', max_length=20)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_documents', to='legal_path.legalrequest')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='ai_assistant.documenttemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
