# Generated by Django 6.0.6 on 2026-06-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_writer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
